language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
rust:
  - stable
  - beta
  - nightly
cache: cargo
before_script:
  - (cargo install rustfmt || true)
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH
script:
  - export PATH=$PATH:~/.cargo/bin
  - travis-cargo fmt -- --write-mode=diff
  - travis-cargo build --verbose
  - travis-cargo test --verbose
  - travis-cargo --only stable doc
after_success:
  - travis-cargo coveralls --no-sudo --verify
matrix:
  allow_failures:
    - rust: nightly
