sudo: false
language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake
rust:
  - stable
  - beta
  - nightly
cache: cargo
before_script:
  - (cargo install rustfmt || true)
  - (cargo install cargo-travis || true)
  - export PATH=$HOME/.cargo/bin:$PATH
script:
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose
after_success:
  - cargo coveralls
matrix:
  allow_failures:
    - rust: nightly
