language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
before_script: cargo install -f rustfmt
script:
- |
  cargo fmt -- --write-mode=diff &&
  cargo build --verbose &&
  cargo test --verbose
matrix:
  allow_failures:
    - rust: nightly
