[package]
name = "rpg"
version = "0.0.1"
authors = ["Julian Laubstein <contact@julianlaubstein.de>"]

[dependencies]
rand = "0.3.14"
names = "0.11.0"
rustc-serialize = "0.3.21"
prettytable-rs = "0.6.6"
term = "0.4.4"
